dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: KjZIvKovP2/rnaPPzWQYQBvSUmjo4KFJyP/RSqU+uvFfvq2VwPTlEJXKQDiwZuFDWXJKtvZnmyIHjcX6ZhvqbGQro7s7S/OqROZL/X6OvfXEMavXs+1SRuUx50PYJOjb15ttD+i00lthXZ8PwBv7eaDCXBAGhPnCFYBAvr7rBkodrXy2hW9tA9EELrIelc3Uvd9qO7O8p0w7ztBNwo1UD+rdEC0hy5tTlKbCSc80Z3AU+n+FkX9sEgBsZQPX+R6dHZYjrT4wn2p/VizeudOXa6FtMLxyM53uKpsg0IkHwCGXMg/yS3CsmSOS2gpyiFbVlVPPXnEe95r2XiRrIwuw35KvANK4chY2uKIOO7VSFzDLE2u7C9h/xL8yoGl8Dwk3DryoOgFOWSOvh+yyV9uy9XukRS3E2FFngxwpVDEApISH9WkKKilWhm4xhAiOgimA0KmFAcz1Od4DFzXk8+DyDYKjjAEW0jmozjiEvsi8+y/6Bv5fQisOwdexjiSh34JpcXzo6flsB28j6mSHqubXD59/9NQSJ5IRMwP9P7rRnsY8ci8g5QUYZL1Hp16khd/APuOf/7w36svvGz+aNEjwB7x9CDJ2/dIZdZdJdq93aavQ9dXI8of0vpWGSA6SfvGzaJllIieVQtPcMtbQ5UNeSMiNpVvmFAi2WyayzEknm+M=
