dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    secure: M+yKPJHzbvjF/VYmpbLGUzDZY/j39EoQP3boeojpoZDjbAv4PwnjeaFGHANfu2cLixfxZRSWfi23YFdRnWt00w7OiQ5G0ERabFCuOz11ZMepb+tMsExDhi2ioP3t8RSiQQf7JAfU/9vcDaP79BdQUjId/PIbWQ45SxuwcWHI4T2YhE4fYmNSBNJVMSkntro3Tc3dy8cu8QWJ94otzoLaXPrJ96xbbpLGAxzAgFKaYaYsXeWS7w3geXiXyUkkUWeIzBorrXOupz6ipeBUn75agZj9ucVuKqtQtOqadyl0hBNv+Qc3tAPUV2HYyC00Vm9FwyLEhpXpAnwJ4lsNkW9GzY2zxCc+8LQgVsOggBz0rVA0/njgzzUHLRxCAH7FRQnDkfXk9T5eThGMSp/MilfteEMIJnrExRUlx1TgjjfKmxC9YN4Gz3D95T68cw9HdKA77Cibreg3IKEwKFruoG8GyukEwiMJrpaE/FFyLOSDjfPW56gGPYNm3aYIZDz82ziV30Oix7ahDsZiNW/Gcy4EKOMDESuNHIOC9srYv98QqgMlOLibezCV7pIkfN2dxYdnVCjBL1LSoDV4twQlZc5v6MBCOKcSTXhDs7vDKS1i4qL8tIKdOEXVkaX1MoeVZp+MzZvunEI7Lag0nCArdjzlkA4/QMZY3AMf97SwRcke1C8=
