global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#nikita_shvyryaev'
