version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      backend:
        aliases:
          - comment_db
  ui:
    image: ${USER_NAME}/ui:${UI_VERSION}
    environment:
      - ZIPKIN_ENABLED
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - frontend
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
  post:
    image: ${USER_NAME}/post:${POST_VERSION}
    environment:
      - ZIPKIN_ENABLED
    networks:
      - backend
      - frontend
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
  comment:
    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    environment:
      - ZIPKIN_ENABLED
    networks:
      - backend
      - frontend

volumes:
  post_db:

networks:
  backend:
  frontend:
