version: '3.3'
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - frontend
      - backend

  fluentd:
    image: ${USER_NAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - logging_net

  elasticsearch:
    image: elasticsearch:7.4.0
    environment:
      # single-node mode for testing and development
      # production mode requires many settings to be configured
      - discovery.type=single-node
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      - logging_net

  kibana:
    image: kibana:7.4.0
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - logging_net

networks:
  logging_net:
  backend:
  frontend:
