version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      backend:
        aliases:
          - comment_db
  ui:
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - frontend
  post:
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - backend
      - frontend
  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - backend
      - frontend
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    networks:
      - backend
      - frontend
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - frontend
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
  mongodb_exporter:
    image: bitnami/mongodb-exporter:${VERSION_MONGODB_EXPORTER:-latest}
    environment:
      - MONGODB_URI=mongodb://comment_db:27017
    networks:
      - backend
  blackbox_exporter:
    image: ${USERNAME}/blackbox-exporter:${VERSION_BLACKBOX_EXPORTER:-latest}
    ports:
      - '9115:9115'
    networks:
      - frontend
      - backend

volumes:
  post_db:
  prometheus_data:

networks:
  backend:
  frontend:
