kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: wOchYcuT1nQqaTbQx9p+Tfsd45AkAo4QYcv+D9a0hrg=
      - identity: {}
